services:
    trinity.widgets.manager:
      class: Trinity\WidgetsBundle\Widget\WidgetManager
      arguments:
          - @service_container
      synchronized: true
      calls:
        - [setRequest, ["@?request="]]
      tags:
         - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }


    trinity.widgets.extension:
      class: Trinity\WidgetsBundle\Twig\WidgetExtension
      arguments: [ "@trinity.widgets.manager" ]
      public: true
      tags:
        - {name: twig.extension}


    trinity.widgets.dashboard.form.dashboard_type:
      class: Trinity\WidgetsBundle\Form\DashboardType
      arguments: [ @trinity.widgets.manager ]
      tags:
        - {name: form.type, alias: trinity_widgets_bundle_dashboard_type}
