services:
    trinity.widgets.manager:
      class: Trinity\WidgetsBundle\Widget\WidgetManager


    trinity.widgets.extension:
      class: Trinity\WidgetsBundle\Twig\WidgetExtension
      arguments: [ "@trinity.widgets.manager" ]
      public: true
      tags:
        - {name: twig.extension}