services:
    trinity.widgets_manager:
      class: Trinity\WidgetsBundle\Widget\WidgetManager
      arguments: ["@event_dispatcher"]


    trinity.widgets.extension:
      class: Trinity\WidgetsBundle\Twig\WidgetExtension
      arguments: ["@service_container", "@trinity.widgets_manager"]
      tags:
        - {name: twig.extension}