services:

    trinity.widgets.manager:
      class: Trinity\Bundle\WidgetsBundle\Widget\WidgetManager
      arguments:
        - "@router"
        - "@security.token_storage"
        - "@doctrine.orm.entity_manager"
        - "@form.factory"
        - "@request_stack"
      lazy: true  
      tags:
         - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }


    trinity.widgets.extension:
      class: Trinity\Bundle\WidgetsBundle\Twig\WidgetExtension
      arguments:
        - "@trinity.widgets.manager"
        - "@router"
        - "@request_stack"
        - "@logger"
      public: true
      calls:
        - [setConfig, [{"cache": {"enabled": "%widgets.cache.enabled%", "service": "@cache.app", "cache_expiration_time" : "%widgets.cache.cache_expiration_time%" }}]]
      tags:
        - {name: twig.extension}

    trinity.widgets.dashboard.form.dashboard_type:
      class: Trinity\Bundle\WidgetsBundle\Form\DashboardType
      arguments: [ "@trinity.widgets.manager"]
      tags:
        - {name: form.type, alias: trinity_widgets_bundle_dashboard_type}

    trinity.twig.extension.loader:
        class: Twig_Extension_StringLoader
        tags:
             - { name: 'twig.extension' }

