<?php

namespace Trinity\Bundle\WidgetsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetsSettingsManagerRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class WidgetsSettingsManagerRepository extends EntityRepository
{
}
